import { ensureSchema } from '../_lib/db.js';
const CATEGORY_LINKS={Scholarship:'/scholarships',Admission:'/admissions',Internship:'/internships',Fellowship:'/fellowships',Job:'/jobs',Scheme:'/schemes',Update:'/updates'};
const CATEGORY_COVERS={Scholarship:'/assets/img/covers/scholarship.svg',Admission:'/assets/img/covers/admission.svg',Internship:'/assets/img/covers/internship.svg',Fellowship:'/assets/img/covers/fellowship.svg',Job:'/assets/img/covers/job.svg',Scheme:'/assets/img/covers/scheme.svg',Update:'/assets/img/covers/update.svg'};
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function paragraphs(s=''){return String(s).split(/\n{2,}/).map(x=>x.trim()).filter(Boolean).map(x=>`<p>${esc(x).replace(/\n/g,'<br>')}</p>`).join('');}
function safeUrl(s=''){try{const u=new URL(String(s));return /^https?:$/.test(u.protocol)?u.href:'';}catch{return '';}}
function safeImage(s=''){try{const u=new URL(String(s));return u.protocol==='https:'?u.href:'';}catch{return '';}}
function normalizedUrl(s=''){const x=safeUrl(s);if(!x)return '';try{const u=new URL(x);u.hash='';return u.href.replace(/\/$/,'');}catch{return '';}}
function dateText(v=''){if(!v)return 'Not specified';const d=new Date(v);return Number.isNaN(d.getTime())?esc(v):d.toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric'});}
export async function onRequestGet(context){
  await ensureSchema(context.env);
  if(!context.env.DB)return new Response('Database is not configured.',{status:503});
  const slug=String(context.params.slug||'');
  const o=await context.env.DB.prepare(`SELECT * FROM opportunities
    WHERE slug=? AND status='published'
      AND LENGTH(TRIM(title))>=5
      AND LOWER(TRIM(title)) NOT IN ('home','homepage','home page','funding','funding option','funding options','funding programme','funding programmes','funding program','funding programs','scholarship','scholarships','fellowship','fellowships','internship','internships','admission','admissions','job','jobs','scheme','schemes','update','updates','opportunity','opportunities','programme','programmes','program','programs','read more','learn more','apply now','view details','click here','overview','search','news','all','more','menu','finding scholarships','find scholarships','search scholarships','scholarship search','scholarship database','funding database','find funding','search funding','funding opportunities','study scholarships','study funding','programme search','program search','course search','search programmes','search programs','all scholarships','all opportunities','opportunity search')
    LIMIT 1`).bind(slug).first();
  if(!o)return new Response(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="robots" content="noindex"><title>Opportunity not found | OpportunityTrack</title><link rel="stylesheet" href="/assets/css/styles.css"></head><body><main class="main"><section class="article"><h1>Opportunity not found</h1><p>This opportunity may have been removed, unpublished, or renamed.</p><p><a href="/">Return to OpportunityTrack</a></p></section></main></body></html>`,{status:404,headers:{'content-type':'text/html; charset=utf-8'}});
  const origin=new URL(context.request.url).origin;
  const canonical=`${origin}/opportunities/${encodeURIComponent(o.slug)}`;
  const categoryLink=CATEGORY_LINKS[o.category]||'/updates';
  const source=safeUrl(o.official_source);
  const applyRaw=safeUrl(o.application_link);
  const apply=applyRaw && normalizedUrl(applyRaw)!==normalizedUrl(source)?applyRaw:'';
  const poster=`${origin}/poster/${encodeURIComponent(o.slug)}`;
  const cover=safeImage(o.image_url)||poster;
  const schema=JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:o.title,description:o.short_description,image:[cover],datePublished:o.published_date||o.created_at,dateModified:o.updated_at,mainEntityOfPage:canonical,publisher:{'@type':'Organization',name:'OpportunityTrack',url:origin}}).replace(/</g,'\\u003c');
  const applyTop=apply?`<a class="btn detail-apply-btn" href="${esc(apply)}" target="_blank" rel="nofollow noopener noreferrer">Apply now ↗</a>`:'<span class="application-unavailable">Direct application link not yet verified</span>';
  const sourceNote=source?`<p class="verification-source">Information was checked against the <a href="${esc(source)}" target="_blank" rel="nofollow noopener noreferrer">official programme notice</a>. OpportunityTrack provides its own structured summary and application guidance.</p>`:'';
  const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(o.title)} | OpportunityTrack</title><meta name="description" content="${esc(String(o.short_description||'').slice(0,160))}"><meta name="google-adsense-account" content="ca-pub-6230254905056654"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="article"><meta property="og:site_name" content="OpportunityTrack"><meta property="og:title" content="${esc(o.title)}"><meta property="og:description" content="${esc(String(o.short_description||'').slice(0,200))}"><meta property="og:image" content="${esc(cover)}"><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#1d4f73"><link rel="icon" href="/assets/img/logo.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/css/styles.css"><script type="application/ld+json">${schema}</script></head><body><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="nav-wrap"><a class="brand" href="/" aria-label="OpportunityTrack home"><span class="brand-mark">O</span><span>OpportunityTrack</span></a><nav class="nav-links" data-nav aria-label="Primary navigation"><a href="/scholarships">Scholarships</a><a href="/admissions">Admissions</a><a href="/internships">Internships</a><a href="/fellowships">Fellowships</a><a href="/jobs">Jobs</a><a href="/schemes">Schemes</a><a href="/updates">Updates</a><a href="/guides">Guides</a><a href="/about">About</a></nav><div class="nav-actions"><button class="icon-btn" type="button" data-open-search aria-label="Search site">Search</button><button class="menu-btn" type="button" data-menu aria-expanded="false">Menu</button></div></div></header>
<section class="page-hero opportunity-hero"><div class="inner"><div class="opportunity-hero-grid"><div class="opportunity-hero-copy"><div class="breadcrumbs"><a href="/">Home</a> / <a href="${categoryLink}">${esc(o.category)}</a> / Opportunity</div><div class="kicker">${esc(o.category)}${o.featured?' · Featured':''}</div><h1>${esc(o.title)}</h1><p>${esc(o.short_description)}</p><div class="hero-op-actions">${applyTop}<a class="btn secondary" href="#details">View details</a></div></div><div class="opportunity-hero-media"><img src="${esc(cover)}" data-fallback="${esc(poster)}" alt="${esc(o.title)} poster" decoding="async" fetchpriority="high" referrerpolicy="no-referrer" onerror="if(this.src!==this.dataset.fallback)this.src=this.dataset.fallback"></div></div></div></section>
<main class="main" id="main"><div class="content-layout"><article class="article opportunity-detail-article"><div id="details" class="opportunity-detail-meta"><div class="detail-box"><span>Organization</span><strong>${esc(o.organization||'Not specified')}</strong></div><div class="detail-box"><span>Location</span><strong>${esc([o.city,o.country].filter(Boolean).join(', ')||'Not specified')}</strong></div><div class="detail-box"><span>Funding / Type</span><strong>${esc(o.funding||o.degree_level||'See details')}</strong></div><div class="detail-box"><span>Deadline</span><strong>${esc(o.deadline||'Not specified')}</strong></div></div>
<h2>Opportunity overview</h2><p>${esc(o.short_description)}</p>${o.eligibility?`<h2>Eligibility</h2>${paragraphs(o.eligibility)}`:''}${o.full_details?`<h2>Details</h2>${paragraphs(o.full_details)}`:''}<h2>How to apply</h2><p>Read the eligibility and document requirements above, prepare the requested materials, and use the verified application route below. Application requirements and deadlines can change, so review the programme instructions before submitting.</p><div class="source-actions">${apply?`<a class="btn detail-apply-btn" href="${esc(apply)}" target="_blank" rel="nofollow noopener noreferrer">Apply now ↗</a>`:'<span class="application-unavailable">A direct application portal was not verified for this listing yet.</span>'}</div><div class="note"><strong>Application check:</strong> OpportunityTrack organizes the listing into a consistent format to help you compare opportunities. Always confirm the final deadline, eligibility, required documents, and submission steps before applying.</div>${sourceNote}</article><aside class="sidebar"><div class="side-card"><h3>Opportunity details</h3><p class="muted"><strong>Published:</strong> ${dateText(o.published_date||o.created_at)}</p><p class="muted"><strong>Category:</strong> ${esc(o.category)}</p>${o.degree_level?`<p class="muted"><strong>Level:</strong> ${esc(o.degree_level)}</p>`:''}${o.tags?`<p class="muted"><strong>Tags:</strong> ${esc(o.tags)}</p>`:''}${apply?`<a class="btn side-apply" href="${esc(apply)}" target="_blank" rel="nofollow noopener noreferrer">Apply now ↗</a>`:''}</div><div class="side-card"><h3>Explore more</h3><a href="${categoryLink}">More ${esc(o.category)} opportunities</a><a href="/updates">Latest updates</a><a href="/guides">Application guides</a><a href="/faq">FAQ</a></div></aside></div></main>
<footer class="site-footer"><div class="footer-inner"><div class="footer-brand"><a class="brand" href="/" style="color:white"><span class="brand-mark">O</span><span>OpportunityTrack</span></a><p>Global opportunity discovery and practical application guidance for students and professionals worldwide.</p></div><div class="footer-col"><h3>Opportunities</h3><a href="/scholarships">Scholarships</a><a href="/admissions">Admissions</a><a href="/internships">Internships</a><a href="/fellowships">Fellowships</a><a href="/jobs">Jobs</a><a href="/schemes">Schemes</a></div><div class="footer-col"><h3>Resources</h3><a href="/updates">Updates</a><a href="/guides">Guides</a><a href="/faq">FAQ</a><a href="/contact">Contact</a></div><div class="footer-col"><h3>Site</h3><a href="/about">About</a><a href="/privacy-policy">Privacy Policy</a><a href="/sitemap.xml">Sitemap</a></div></div><div class="footer-bottom"><span>© 2026 OpportunityTrack. All rights reserved.</span><span>Check application requirements before submitting.</span></div></footer><div class="search-overlay" data-search-overlay aria-hidden="true"><div class="search-box" role="dialog" aria-modal="true"><div class="search-top"><input type="search" data-search-input placeholder="Search opportunities and guides"><button class="icon-btn" type="button" data-close-search>Close</button></div><div class="search-results" data-search-results></div></div></div><script src="/assets/js/search-index.js" defer></script><script src="/assets/js/site.js" defer></script></body></html>`;
  return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=15'}});
}
