import { ensureSchema } from '../_lib/db.js';
const CATEGORY_LINKS={Scholarship:'/scholarships.html',Admission:'/admissions.html',Internship:'/internships.html',Fellowship:'/fellowships.html',Job:'/jobs.html',Scheme:'/schemes.html',Update:'/updates.html'};
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function paragraphs(s=''){return String(s).split(/\n{2,}/).map(x=>x.trim()).filter(Boolean).map(x=>`<p>${esc(x).replace(/\n/g,'<br>')}</p>`).join('');}
function safeUrl(s=''){try{const u=new URL(String(s));return /^https?:$/.test(u.protocol)?u.href:'';}catch{return '';}}
function dateText(v=''){if(!v)return 'Not specified';const d=new Date(v);return Number.isNaN(d.getTime())?esc(v):d.toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric'});}
export async function onRequestGet(context){
  await ensureSchema(context.env);
  if(!context.env.DB)return new Response('Database is not configured.',{status:503});
  const slug=String(context.params.slug||'');
  const o=await context.env.DB.prepare("SELECT * FROM opportunities WHERE slug=? AND status='published' LIMIT 1").bind(slug).first();
  if(!o)return new Response(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="robots" content="noindex"><title>Opportunity not found | OpportunityTrack</title><link rel="stylesheet" href="/assets/css/styles.css"></head><body><main class="main"><section class="article"><h1>Opportunity not found</h1><p>This opportunity may have been removed, unpublished, or renamed.</p><p><a href="/">Return to OpportunityTrack</a></p></section></main></body></html>`,{status:404,headers:{'content-type':'text/html; charset=utf-8'}});
  const origin=new URL(context.request.url).origin;const canonical=`${origin}/opportunities/${encodeURIComponent(o.slug)}`;const categoryLink=CATEGORY_LINKS[o.category]||'/updates.html';const apply=safeUrl(o.application_link),source=safeUrl(o.official_source);
  const schema=JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:o.title,description:o.short_description,datePublished:o.published_date||o.created_at,dateModified:o.updated_at,mainEntityOfPage:canonical,publisher:{'@type':'Organization',name:'OpportunityTrack',url:origin}}).replace(/</g,'\\u003c');
  const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(o.title)} | OpportunityTrack</title><meta name="description" content="${esc(o.short_description).slice(0,160)}"><meta name="google-adsense-account" content="ca-pub-6230254905056654"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="article"><meta property="og:site_name" content="OpportunityTrack"><meta property="og:title" content="${esc(o.title)}"><meta property="og:description" content="${esc(o.short_description).slice(0,200)}"><meta name="theme-color" content="#1d4f73"><link rel="icon" href="/assets/img/logo.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/css/styles.css"><script type="application/ld+json">${schema}</script></head><body><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="nav-wrap"><a class="brand" href="/" aria-label="OpportunityTrack home"><span class="brand-mark">O</span><span>OpportunityTrack</span></a><nav class="nav-links" data-nav aria-label="Primary navigation"><a href="/scholarships.html">Scholarships</a><a href="/admissions.html">Admissions</a><a href="/internships.html">Internships</a><a href="/fellowships.html">Fellowships</a><a href="/jobs.html">Jobs</a><a href="/schemes.html">Schemes</a><a href="/updates.html">Updates</a><a href="/guides.html">Guides</a><a href="/about.html">About</a></nav><div class="nav-actions"><button class="icon-btn" type="button" data-open-search aria-label="Search site">Search</button><button class="menu-btn" type="button" data-menu aria-expanded="false">Menu</button></div></div></header>
<section class="page-hero"><div class="inner"><div class="breadcrumbs"><a href="/">Home</a> / <a href="${categoryLink}">${esc(o.category)}</a> / Opportunity</div><div class="kicker">${esc(o.category)}${o.featured?' · Featured':''}</div><h1>${esc(o.title)}</h1><p>${esc(o.short_description)}</p></div></section>
<main class="main" id="main"><div class="content-layout"><article class="article"><div class="opportunity-detail-meta"><div class="detail-box"><span>Organization</span><strong>${esc(o.organization||'Not specified')}</strong></div><div class="detail-box"><span>Country</span><strong>${esc([o.city,o.country].filter(Boolean).join(', ')||'Not specified')}</strong></div><div class="detail-box"><span>Funding / Type</span><strong>${esc(o.funding||o.degree_level||'See official source')}</strong></div><div class="detail-box"><span>Deadline</span><strong>${esc(o.deadline||'Check official source')}</strong></div></div>
<h2>Opportunity overview</h2><p>${esc(o.short_description)}</p>${o.eligibility?`<h2>Eligibility</h2>${paragraphs(o.eligibility)}`:''}${o.full_details?`<h2>Details</h2>${paragraphs(o.full_details)}`:''}<h2>How to apply</h2><p>Review the official provider page before submitting an application. Confirm the current eligibility criteria, deadline, required documents, funding or employment terms, and the official submission route.</p><div class="source-actions">${apply?`<a class="btn" href="${esc(apply)}" target="_blank" rel="noopener noreferrer">Open application link</a>`:''}${source?`<a class="btn secondary" href="${esc(source)}" target="_blank" rel="noopener noreferrer">Verify official source</a>`:''}</div><div class="note"><strong>Verification note:</strong> OpportunityTrack summarizes information for planning purposes. Details can change, so always rely on the official provider for the final requirements and deadline.</div></article><aside class="sidebar"><div class="side-card"><h3>Opportunity details</h3><p class="muted"><strong>Published:</strong> ${dateText(o.published_date||o.created_at)}</p><p class="muted"><strong>Category:</strong> ${esc(o.category)}</p>${o.degree_level?`<p class="muted"><strong>Level:</strong> ${esc(o.degree_level)}</p>`:''}${o.tags?`<p class="muted"><strong>Tags:</strong> ${esc(o.tags)}</p>`:''}</div><div class="side-card"><h3>Explore more</h3><a href="${categoryLink}">More ${esc(o.category)} opportunities</a><a href="/updates.html">Latest updates</a><a href="/guides.html">Application guides</a><a href="/faq.html">FAQ</a></div></aside></div></main>
<footer class="site-footer"><div class="footer-inner"><div class="footer-brand"><a class="brand" href="/" style="color:white"><span class="brand-mark">O</span><span>OpportunityTrack</span></a><p>Verified-source opportunity discovery and practical application guidance for students and professionals worldwide.</p></div><div class="footer-col"><h3>Opportunities</h3><a href="/scholarships.html">Scholarships</a><a href="/admissions.html">Admissions</a><a href="/internships.html">Internships</a><a href="/fellowships.html">Fellowships</a><a href="/jobs.html">Jobs</a><a href="/schemes.html">Schemes</a></div><div class="footer-col"><h3>Resources</h3><a href="/updates.html">Updates</a><a href="/guides.html">Guides</a><a href="/faq.html">FAQ</a><a href="/contact.html">Contact</a></div><div class="footer-col"><h3>Site</h3><a href="/about.html">About</a><a href="/privacy-policy.html">Privacy Policy</a><a href="/sitemap.xml">Sitemap</a></div></div><div class="footer-bottom"><span>© 2026 OpportunityTrack. All rights reserved.</span><span>Always verify details with the official provider.</span></div></footer><div class="search-overlay" data-search-overlay aria-hidden="true"><div class="search-box" role="dialog" aria-modal="true"><div class="search-top"><input type="search" data-search-input placeholder="Search opportunities and guides"><button class="icon-btn" type="button" data-close-search>Close</button></div><div class="search-results" data-search-results></div></div></div><script src="/assets/js/search-index.js" defer></script><script src="/assets/js/site.js" defer></script></body></html>`;
  return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=15'}});
}
